---
cops_{{cookiecutter.app_type}}_deploy_env: dev
cops_{{cookiecutter.app_type}}_hostname:  "{{cookiecutter.dev_domain}}"
cops_{{cookiecutter.app_type}}_alternate_hostnames: {{cookiecutter.dev_alternate_domains.split(',')}}
