ignore:
  - {{cookiecutter.lname}}.email_notif
  - {{cookiecutter.lname}}.pardot_config
  - block.block.{{cookiecutter.lname}}_theme_contribution
  - block.block.{{cookiecutter.lname}}_theme_latest_extensions
  - devel.*
  - google_analytics.settings
  - google_tag.settings
  - pardot.settings
  - system.logging
  - system.menu.devel
  - system.performance
  - system.site
