---
ssh_envs:
  vars:
    sudo_flags: "-HE"
    ansible_port: 22
    ansible_user: root
    ansible_ssh_common_args: "-i {{'{{'}}cops_deploy_ssh_key_paths['deploy'].path}} -p {{'{{'}}ansible_port}} -o IdentitiesOnly=yes"
  hosts:
{% for i in ['dev', 'prod', 'qa', 'staging'] %}{% if
  cookiecutter['{0}_host'.format(i)]%}    {{cookiecutter['{0}_host'.format(i)]}}:
      ansible_port: "{{cookiecutter['{0}_port'.format(i)]}}"
{%endif%}{%endfor%}
{%- for i in ['dev', 'prod', 'qa', 'staging'] %}
{%- if cookiecutter['{0}_host'.format(i)]%}{{i}}:
  hosts:
    {{cookiecutter['{0}_host'.format(i)]}}:
{% endif -%}
{% endfor -%}
{{cookiecutter.lname}}_servers:
  children:
{% for i in ['dev', 'prod', 'qa', 'staging'] %}{%
        if cookiecutter['{0}_host'.format(i)]%}    {{i}}:
{% endif -%}
{% endfor -%}
{{-cookiecutter.app_type}}_servers: {children: {{'{'}}{{cookiecutter.lname}}_servers: null}}
app_servers: {children: {{'{'}}{{cookiecutter.app_type}}_servers: null}}
{{cookiecutter.app_type}}:
  children:
    controller:
    app_servers:
{{cookiecutter.lname}}:
  children:
    {{cookiecutter.app_type}}:
controller: {hosts: {localhost: {ansible_connection: local}}}
