---
ssh_envs:
  vars:
    ansible_bastion: ""
    ansible_bastion_user: ""
    sudo_flags: "-HE"
    ansible_port: 22
    ansible_user: root
    ansible_ssh_bastion: "{{'{%'}}if ansible_bastion%}-o ProxyCommand=\"ssh -i {{'{{'}}cops_deploy_ssh_key_paths['deploy'].path}} -o IdentitiesOnly=yes -q -W {{'{{'}}ansible_host}}:{{'{{'}}ansible_port}} {{'{{'}}ansible_bastion}} {{'{%'}}if ansible_bastion_user%}-l {{'{{'}}ansible_bastion_user}}{{'{%'}}endif%} -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no\" {{'{%'}}endif%}"
    ansible_ssh_common_args: "{{'{{'}}ansible_ssh_bastion}}-i {{'{{'}}cops_deploy_ssh_key_paths['deploy'].path}} -p {{'{{'}}ansible_port}} -o IdentitiesOnly=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  children:
    bastion:
      vars:
        ansible_bastion: bastionhost
        ansible_bastion_user: bastionuser
      hosts:
        # a_host_with_bastion:
  hosts:
{% for i in ['dev', 'prod', 'qa', 'staging', 'preprod'] %}{% if
  cookiecutter['{0}_host'.format(i)]%}    {{cookiecutter['{0}_host'.format(i)]}}:
      ansible_port: "{{cookiecutter['{0}_port'.format(i)]}}"
{%endif%}{%endfor%}
{%- for i in ['dev', 'prod', 'qa', 'staging', 'preprod'] %}
{%- if cookiecutter['{0}_host'.format(i)]%}{{i}}:
  hosts:
    {{cookiecutter['{0}_host'.format(i)]}}:
{% endif -%}
{% endfor -%}
{{cookiecutter.lname}}_servers:
  children:
{% for i in ['dev', 'prod', 'qa', 'staging', 'preprod'] %}{%
        if cookiecutter['{0}_host'.format(i)]%}    {{i}}:
{% endif -%}
{% endfor -%}
{{-cookiecutter.app_type}}_servers: {children: {{'{'}}{{cookiecutter.lname}}_servers: null}}
app_servers: {children: {{'{'}}{{cookiecutter.app_type}}_servers: null}}
{{cookiecutter.app_type}}:
  children:
    controller:
    app_servers:
{{cookiecutter.lname}}:
  children:
    {{cookiecutter.app_type}}:
controller: {hosts: {localhost: {ansible_connection: local}}}
