version: '{{cookiecutter.compose_version}}'
{%- set db_tag = 'post' in cookiecutter.db_mode and 'postgres' or cookiecutter.db_mode %}
x-images:
  env: &env
    env_file: [ .env, docker.env ]
    environment: &env_vars
      DB_MODE: "${DB_MODE:-{{cookiecutter.db_mode}}}"
      PHP_USER: "${PHP_USER-{{cookiecutter.php_user}}}"
      PHP_GROUP: "${PHP_GROUP-{{cookiecutter.php_group}}}"
      DRUPAL_ENV_NAME: "${DRUPAL_ENV_NAME-prod}"
      APP_SECRET: "${APP_SECRET-77fd8b950969a6909c46ab0b6fd5d062}"
      IMAGE_MODE: phpfpm
      APP_TYPE: {{cookiecutter.app_type}}
      # docker variables that can be overriden via .env/docker.env
      # This need to be changed in production
      MAILCATCHER_USER: "${MAILCATCHER_USER-mailcatcher}"
      MAILCATCHER_PASSWORD: "${MAILCATCHER_PASSWORD-mailcatcher}"
      # parsed/replaced in CI via env-subst
      # Used in INSTALL ---------------
      PROFILE_NAME: "${PROFILE_NAME-{{ cookiecutter.profile_name }}}"
      SITE_NAME: "${SITE_NAME-{{ cookiecutter.site_name }}}"
      SITE_MAIL: "${SITE_MAIL-contact@{{ cookiecutter.mail_domain }}}"
      ADMIN_MAIL: "${ADMIN_MAIL-sysadmin+{{ cookiecutter.lname }}@{{ cookiecutter.mail_domain }}}"
      ADMIN_NAME: "${ADMIN_NAME-admin}"
      # ADMIN_PASS is set via ansible(and graved into .env) in production
      ADMIN_PASS: "${ADMIN_PASS-admin}"
      # or any other documented way before running install script
      SITE_DEFAULT_COUNTRY: "${SITE_DEFAULT_COUNTRY-FR}"
      DATE_DEFAULT_TIMEZONE: "${DATE_DEFAULT_TIMEZONE-Europe/Paris}"
      UPDATE_STATUS_MODULE: "${UPDATE_STATUS_MODULE-0}"
      DRUPAL_NAME: "${DRUPAL_NAME-{{ cookiecutter.drupal_project_name }}}"
      DRUPAL_URI: "${DRUPAL_URI-http://{{cookiecutter.local_domain}}:{{cookiecutter.local_http_port}}}"
      DRUSH_EXTRA_ARGS: "${DRUSH_EXTRA_ARGS- --uri=http://{{cookiecutter.local_domain}}:{{cookiecutter.local_http_port}}}"
      # Key settings ------------------
      NGINX_SERVERNAME: "${NGINX_SERVERNAME-{{cookiecutter.local_domain}}}"
      NGINX_SERVER_ALIASES: "${NGINX_SERVER_ALIASES-www.{{cookiecutter.local_domain}} www2.{{cookiecutter.local_domain}}}"
      DRUPAL__ALLOWED_HOSTS: "${DRUPAL__ALLOWED_HOSTS-{{cookiecutter.local_domain.replace(".","\\\\.")}}|www\\.{{cookiecutter.local_domain.replace(".","\\\\.")}}|www2\\.{{cookiecutter.local_domain.replace(".","\\\\.")}}}"
      DRUPAL__HTTP_PROTECT_USER: "${DRUPAL__HTTP_PROTECT_USER-}"
      DRUPAL__HTTP_PROTECT_PASSWORD: "${DRUPAL__HTTP_PROTECT_PASSWORD-}"
      DATABASE_PREFIX: "${DATABASE_PREFIX-}"
{% if 'post' in cookiecutter.db_mode %}
      POSTGRES_STARTUP_TIMEOUT: "${POSTGRES_STARTUP_TIMEOUT-45s}"
      POSTGRES_HOST: "${POSTGRES_HOST-db}"
      POSTGRES_PORT: "${POSTGRES_PORT-5432}"
      POSTGRES_DB: "${POSTGRES_DB-db}"
      POSTGRES_USER: "${POSTGRES_USER-user}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD-password}"
      PGPASSWD: "${POSTGRES_PASSWORD-password}"
      PGPASSWORD: "${POSTGRES_PASSWORD-password}"
      DATABASE_DRIVER: "${DATABASE_DRIVER-pgsql}"
      DATABASE_DB: "${POSTGRES_DB-db}"
      DATABASE_USER: "${POSTGRES_USER-user}"
      DATABASE_PASSWD: "${POSTGRES_PASSWORD-password}"
      DATABASE_HOST: "${POSTGRES_HOST-db}"
      DATABASE_PORT: "${POSTGRES_PORT-5432}"
{% elif 'mysql' in cookiecutter.db_mode %}
      MYSQL_HOST: "${MYSQL_HOST-db}"
      MYSQL_PORT: "${MYSQL_PORT-3306}"
      MYSQL_DATABASE: "${MYSQL_DATABASE-db}"
      MYSQL_USER: "${MYSQL_USER-user}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-${MYSQL_PASSWORD:-password}}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD-password}"
      DATABASE_DRIVER: "${DATABASE_DRIVER-mysql}"
      DATABASE_DB: "${MYSQL_DATABASE-db}"
      DATABASE_USER: "${MYSQL_USER-user}"
      DATABASE_PASSWD: "${MYSQL_PASSWORD-password}"
      DATABASE_HOST: "${MYSQL_HOST-db}"
      DATABASE_PORT: "${MYSQL_PORT-3306}"
{%- else %}
      DB_HOST: "${DB_HOST-db}"
      DB_PORT: "${DB_PORT-}"
      DB_NAME: "${DB_NAME-sites/default/files/.ht5.sqlite}"
      DB_USER: "${DB_USER-user}"
      DB_PASSWORD: "${DB_PASSWORD-password}"
      DATABASE_DRIVER: "${DATABASE_DRIVER-sqlite}"
      DATABASE_DB: "${DB_NAME-sites/default/files/.ht5.sqlite}"
      DATABASE_USER: "${DB_USER-user}"
      DATABASE_PASSWD: "${DB_PASSWORD-password}"
      DATABASE_HOST: "${DB_HOST-db}"
      DATABASE_PORT: "${DB_PORT-}"
{%- endif %}
      #
      COOKIE_DOMAIN: "${COOKIE_DOMAIN-{{cookiecutter.local_domain}}}"
      ABSOLUTE_URL_SCHEME: "${ABSOLUTE_URL_SCHEME-http}"
      ABSOLUTE_URL_DOMAIN: "${ABSOLUTE_URL_DOMAIN-{{cookiecutter.local_domain}}}"
      ABSOLUTE_URL_DOMAIN_ESCAPE: "${ABSOLUTE_URL_DOMAIN_ESCAPE-{{cookiecutter.local_domain.replace('.', '\\\\.')}}}"
      ABSOLUTE_URL_PORT: "${ABSOLUTE_URL_PORT-{{cookiecutter.local_http_port}}}"
      #
      PHP_MAX_WORKERS: "${PHP_MAX_WORKERS-10}"
      PHP_MAX_SPARE_WORKERS: "${PHP_MAX_SPARE_WORKERS-5}"
      PHP_MIN_SPARE_WORKERS: "${PHP_MIN_SPARE_WORKERS-3}"
      PHP_XDEBUG_ENABLED: "${PHP_XDEBUG_ENABLED-0}"
      # VARNISH
      VARNISH__HTTP_PROTECT_USER: "${VARNISH__HTTP_PROTECT_USER-}"
      VARNISH__HTTP_PROTECT_PASSWORD: "${VARNISH__HTTP_PROTECT_PASSWORD-}"
      VARNISH_MEMORY_SIZE: "${VARNISH_MEMORY_SIZE-256MB}"
      VARNISH_HIDE_X_CACHE_TAGS: "${VARNISH_HIDE_X_CACHE_TAGS-}"
      VARNISH_BACKENDS: "${VARNISH_BACKENDS-nginx}"
      VARNISH_NO_CACHE_COOKIE: "${VARNISH_NO_CACHE_COOKIE-{{cookiecutter.no_cache_cookie}}}"
      VARNISH_NO_CACHE_URL: "${VARNISH_NO_CACHE_URL-{{cookiecutter.no_cache_url}}}"
      VARNISH_TTL_STATIC: "${VARNISH_TTL_STATIC-3h}"
      VARNISH_TTL_STATIC_BROWSER: "${VARNISH_TTL_STATIC_BROWSER-86400}"
      # Mail
      DRUPAL_SETTINGS__system_DOT_mail___interface_DOT_default: "${DRUPAL_SETTINGS__system_DOT_mail___interface_DOT_default-SMTPMailSystem}"
      DRUPAL_SETTINGS__smtp_DOT_settings___smtp_host: "${DRUPAL_SETTINGS__smtp_DOT_settings___smtp_host-mailcatcher}"
      DRUPAL_SETTINGS__smtp_DOT_settings___smtp_port: "${DRUPAL_SETTINGS__smtp_DOT_settings___smtp_port-1025}"
      DRUPAL_SETTINGS__smtp_DOT_settings___smtp_protocol: "${DRUPAL_SETTINGS__smtp_DOT_settings___smtp_protocol-standard}"
      DRUPAL_SETTINGS__smtp_DOT_settings___smtp_autotls: "${DRUPAL_SETTINGS__smtp_DOT_settings___smtp_autotls-raw:::true}"
      DRUPAL_SETTINGS__smtp_DOT_settings___smtp_username: "${DRUPAL_SETTINGS__smtp_DOT_settings___smtp_username-mailcatcher}"
      DRUPAL_SETTINGS__smtp_DOT_settings___smtp_password: "${DRUPAL_SETTINGS__smtp_DOT_settings___smtp_password-mailcatcher}"
      PHP_MEMORY_LIMIT: "${PHP_MEMORY_LIMIT:-{{cookiecutter.php_memory_limit}}}"
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    <<: [ *env ]
    tty: true
    image: "${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}-dev"
    environment: &{{cookiecutter.app_type}}_env
      <<: [ *env_vars ]
      PROJECT_PACKAGE: "${PROJECT_PACKAGE-{{cookiecutter.drupal_project_name}}}"
      PROJECT_DIR: "${PROJECT_DIR-/code/app}"
    depends_on:
      - db
{%-if cookiecutter.cache_system %}
      - {{cookiecutter.cache_system}}
{%-endif%}
    working_dir: /code/app
    command: [/init.sh]
    volumes:
    - publiccontrib:{{cookiecutter.public_files_path}}/
    - private:{{cookiecutter.private_path}}/
    #- cache:{{cookiecutter.cache_path}}
    # volume that we need to feed for nginx docker
    - webroot:/code/app/var/nginxwebroot
    - "${DATA_VOLUME:-./data}:/code/data"
services:
  log:
    <<: [ *env ]
    image: "{{cookiecutter.rsyslog_image}}"
  mailcatcher:
    <<: [ *env ]
    image: "{{cookiecutter.mailhog_image}}"
    hostname: mailcatcher
    volumes: [ "mails:/mails" ]
{%- if cookiecutter.cache_system %}
  {{cookiecutter.cache_system}}:
    <<: [ *env ]
    image: "{{cookiecutter.cache_image}}"
    hostname: "{{cookiecutter.cache_system}}"
{%- if cookiecutter.cache_system in ['redis'] %}
    volumes:
    - '{{cookiecutter.cache_system}}:/data'
{%- endif %}
{%-endif%}
  db:
    <<: [ *env ]
    image: "{{cookiecutter["{0}_image".format(cookiecutter.db_mode)]}}"
{%- if cookiecutter.db_mode.startswith('post') %}
    entrypoint: ['sh', '-exc', 'docker-entrypoint.sh postgres -N $$POSTGRES_MAX_CONNECTIONS']
{%- endif %}
    environment:
      <<: [ *env_vars ]
{%- if cookiecutter.db_mode.startswith('p') %}
      POSTGRES_MAX_CONNECTIONS: "${POSTGRES_MAX_CONNECTIONS:-2000}"
{%- endif %}
    volumes:
{%- if cookiecutter.db_mode.startswith('p') %}
    - postgresql:/var/lib/postgresql/data
{%- elif cookiecutter.db_mode.startswith('m') %}
    - mysql:/var/lib/mysql
{%- endif %}
{%- if not cookiecutter.remove_varnish%}
  varnish:
    <<: [ *env ]
    # image: "corpusops/varnish"
    image: "${VARNISH_IMAGE}:${VARNISH_IMAGE_VERSION}-dev"
    depends_on: [nginx]
    volumes:
    - ./sys/etc/varnish/varnish.vcl.frep:/docker/sys/etc/varnish/varnish.vcl.frep
{%- endif %}
  nginx:
    <<: [ *env ]
    image: "{{cookiecutter.nginx_image}}"
    depends_on: [{{cookiecutter.app_type}}, mailcatcher]
    volumes:
    - ./sys/etc/nginx/vhost.conf.template:/etc/nginx/conf.d/default.conf.template
    - webroot:{{cookiecutter.public_path}}
    - publiccontrib:{{cookiecutter.public_files_path}}:ro
    - private:{{cookiecutter.private_path}}:ro
    - nginx-certs:/certs
    - "${DATA_VOLUME:-./data}:/code/data"
    # Note: docs not mounted in nginx volume, only php (drupal) can serve it
    # so php can apply security rules on prod access
    environment:
      <<: [ *env_vars ]
      NO_SSL: "0"
      NO_FORCE_SSL: "0"
  {{cookiecutter.app_type}}:
    <<: [ *{{cookiecutter.app_type}} ]
  {%- if not cookiecutter.remove_cron %}
  cron:
    <<: [ *{{cookiecutter.app_type}} ]
    environment:
      <<: [ *{{cookiecutter.app_type}}_env ]
      IMAGE_MODE: cron
      NO_INSTALL: "1"
    depends_on: [{{cookiecutter.app_type}}]
{% endif %}
  backup:
    <<: [ *env ]
    image: "corpusops/dbsmartbackup:{{db_tag}}-{{cookiecutter.db_version}}"
volumes:
{%- if 'post' in cookiecutter.db_mode %}
  postgresql:
{%- elif cookiecutter.db_mode.startswith('m') %}
  mysql:
{%- endif %}
{%-if cookiecutter.cache_system%}
  {{cookiecutter.cache_system}}:
{%-endif%}
  nginx-certs:
  webroot:
  publiccontrib:
  private:
  mails:
