FROM corpusops/ubuntu-bare:20.04

RUN bash -c 'set -ex \
    && : "Install Varnish Package" \
    && apt-get update \
    && apt-get install -y \
      varnish \
    && rm -rf /var/lib/apt/lists/* \
    '

RUN mkdir -p /docker/sys/etc/varnish/

COPY sys/varnish/init.sh /init.sh
COPY sys/etc/varnish/varnish.vcl.frep /docker/sys/etc/varnish/varnish.vcl.frep

RUN chmod u+x /init.sh

WORKDIR /docker/sys

ENTRYPOINT []

CMD "/init.sh"
