version: '3.7'
x-images:
  env: &env {env_file: [.env, docker.env]}
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    build:
      context: "."
      args: &args
        BUILDKIT_INLINE_CACHE: "1"
        BASE: "${DRUPAL_BASE_IMAGE:-{{cookiecutter.base_image}}}"
        # BASE: "${DRUPAL_BASE_IMAGE:-{{cookiecutter.debian_image}}}"
        # BASE: "${DRUPAL_BASE_IMAGE:-{{cookiecutter.centos_image}}}"
        PHP_VER: "${PHP_VER:-{{cookiecutter.php_ver}}}"
        PHP_GROUP: "${PHP_GROUP-{{cookiecutter.php_group}}}"
        PHP_VER_NO_DOT: "${PHP_VER_NO_DOT:-{{cookiecutter.php_ver.replace('.', '') }}}"
        COMPOSER_VERSION: "${COMPOSER_VERSION:-{{cookiecutter.composer_ver}}}"
services:

{%-if not cookiecutter.remove_varnish%}
  varnish:
    <<: [ *env ]
    build: {args: {<<: [ *args ], BASE: "${VARNISH_IMAGE_BASE:-{{cookiecutter.ubuntu_image}}}"}, context: ".", dockerfile: "Dockerfile-Varnish"}
{%-endif%}
{%-if not cookiecutter.remove_doc%}
  docs:
    <<: [ *env, *{{cookiecutter.app_type}} ]
    image: "${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}-docsbuilder"
    build: {args: {<<: [ *args ], PY_VER: "${PY_VER:-3.8}", BASE: "${DOCS_IMAGE_BASE:-{{cookiecutter.ubuntu_image}}}"}, context: ".", dockerfile: "Dockerfile-docs"}
    volumes:
    - ./docs:/code/docs.host
    - ./{{cookiecutter.docs_folder}}:/out
    - ./local:/code/local
    environment:
      BUILDDIR: "${BUILDDIR:-/out}"
      SOURCEDIR: "${SOURCEDIR:-/code/docs.host}"
{%-endif%}
{%- if not cookiecutter.remove_cron %}
  cron: {<<: [ *{{cookiecutter.app_type}} ]}
{%-endif%}
  {{cookiecutter.app_type}}: {<<: [ *{{cookiecutter.app_type}} ]}
  cypress:
    <<: [ *env ]
    image: cypress
    build: ./e2e
    volumes:
    - ./e2e/cypress:/app/cypress
    - ./e2e/cypress.json:/app/cypress.json
