version: '3.7'
x-images:
  env: &env {env_file: [.env, docker.env]}
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    build:
      context: "."
      args:
        PHP_VER: "${PHP_VER:-{{cookiecutter.php_ver}}}"
        PHP_VER_NO_DOT: "${PHP_VER_NO_DOT:-{{cookiecutter.php_ver|replace('.','')}}}"
        COMPOSER_VERSION: "${COMPOSER_VERSION:-{{cookiecutter.composer_ver}}}"
services:
  {%-if not cookiecutter.remove_doc%}
  docs:
    <<: [ *env, *drupal ]
    image: "${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE}:${{'{'}}{{cookiecutter.app_type.upper()}}_IMAGE_VERSION}-dev-docs"
    build: {context: ".", dockerfile: docs/Dockerfile}
    volumes:
    - ./docs:/code/docs.host
    - ./app:/code/app.host
  {%-endif%}
  {%- if not cookiecutter.remove_cron %}
  cron: {<<: [ *{{cookiecutter.app_type}} ]}
  {%-endif%}
  {{cookiecutter.app_type}}: {<<: [ *{{cookiecutter.app_type}} ]}
  cypress:
    <<: [ *env ]
    image: cypress
    build: ./e2e
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.json:/app/cypress.json
