version: '3.7'
x-images:
  bypass: &bypass
    command: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
    entrypoint: 'sh -c "while true;do echo notstarted;sleep 65000;done"'
  {{cookiecutter.app_type}}: &{{cookiecutter.app_type}}
    volumes: &{{cookiecutter.app_type}}_volumes
      - ./app:/code/app.host
      - ./app/public/:/code/app.host/public
      # remount a volume from the hyve VM for better IOs
      - osx-app:/code/app
      - ./app/var/public:/code/app/var/public
      - ./app/var/private:/code/app/var/private
      - osx-cache:/code/app/var/cache
services:
  cron:
    <<: [ *bypass, *{{cookiecutter.app_type}} ]
  {{cookiecutter.app_type}}:
    <<: [ *{{cookiecutter.app_type}} ]
  nginx:
    volumes:
      - ./app:/code/app.host
      - ./app/var/public/:/code/app.host/var/public
      # remount a volume from the hyve VM for better IOs
      - osx-app:/code/app
      - ./app/var/public:/code/app/var/public
      - ./app/var/private:/code/app/var/private
      - osx-var:/code/app/var
      - osx-cache:/code/app/var/cache
volumes:
  osx-app:
  # deep nested volumes need to be reshadowed as well !
  osx-cache:
