---
{{cookiecutter.app_type}}_servers: {{cookiecutter.lname}}_servers
cops_{{cookiecutter.app_type}}_profile_name: "{{cookiecutter.profile_name}}"
cops_{{cookiecutter.app_type}}_name: "{{cookiecutter.lname}}"
cops_{{cookiecutter.app_type}}_tld_domain: "{{cookiecutter.tld_domain}}"
cops_{{cookiecutter.app_type}}_mail_domain: "{{ cookiecutter.mail_domain }}"
cops_{{cookiecutter.app_type}}_docker_image: "{{cookiecutter.docker_image}}"
{%if not cookiecutter.remove_varnish%}
cops_{{cookiecutter.app_type}}_varnish_docker_image: "{{cookiecutter.docker_image}}-varnish"
{% endif %}
cops_{{cookiecutter.app_type}}_gitref: "{{'{{'}}lookup('env', 'CI_COMMIT_TAG_NAME') or lookup('env', 'CI_COMMIT_REF_NAME') or 'latest'}}"
cops_{{cookiecutter.app_type}}_docker_tag: "{{'{{'}}cops_{{cookiecutter.app_type}}_gitref.replace('master', 'latest')}}"
{%if not cookiecutter.remove_varnish%}
cops_{{cookiecutter.app_type}}_varnish_docker_tag: "{{'{{'}}cops_{{cookiecutter.app_type}}_docker_tag }}"
{% endif %}
{% if 'post' in cookiecutter.db_mode -%}
cops_{{cookiecutter.app_type}}_postgres_startup_timeout: 45s
{%- endif %}
cops_{{cookiecutter.app_type}}_dotenv_extra: |-
  # db
  {% if 'post' in cookiecutter.db_mode %}POSTGRES_STARTUP_TIMEOUT={{'{{'}}cops_{{cookiecutter.app_type}}_postgres_startup_timeout}}{% endif %}
cops_drupal_http_protect_user: "root"
cops_drupal_http_protect_password: "rootroot"
{% if not cookiecutter.remove_varnish -%}
cops_drupal_use_varnish: true
{%- endif %}
